name: FancyNpcs
main: de.oliver.FancyNpcs
author: OliverHD
version: 1.1.1
api-version: 1.19
load: POSTWORLD
commands:
  Npc:
    permission: FancyNpcs.admin
    description: Main command for the Npc plugin