name: FancyNpcs
main: de.oliver.fancynpcs.FancyNpcs
author: OliverHD
version: 1.1.4
api-version: 1.19
load: POSTWORLD
commands:
  FancyNpcs:
    permission: FancyNpcs.admin
  Npc:
    permission: FancyNpcs.admin
    description: Main command for the Npc plugin