name: NpcPlugin
main: de.oliver.NpcPlugin
author: OliverHD
version: 1.1.0-BETA
api-version: 1.19
load: POSTWORLD
commands:
  Npc:
    permission: NpcPlugin.admin
    description: Main command for the Npc plugin