name: FancyNpcs
main: de.oliver.fancynpcs.FancyNpcs

author: OliverHD
version: $version

description: $description

api-version: 1.20
folia-supported: true

load: POSTWORLD
softdepend:
  - PlaceholderAPI
  - PlotSquared